"""LaTeX template generator for OpenChapters format.

Takes a Chapter IR object and emits:
- MyChapter.tex (the chapter source file)
- chapter.json (metadata for the OC web interface)
- chaptercitations.bib (bibliography)
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING

from .utils import derive_chabbr, make_label, runs_to_latex, slugify

if TYPE_CHECKING:
    from .model import (
        BibEntry,
        Block,
        Chapter,
        CodeBlock,
        Equation,
        Figure,
        ListBlock,
        ListItem,
        Paragraph,
        Section,
        Table,
    )

# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def generate_chapter_tex(chapter: Chapter, chabbr: str | None = None) -> str:
    """Generate the full MyChapter.tex content."""
    if not chabbr:
        chabbr = derive_chabbr(chapter.title or "MyChapter")

    title = chapter.title or "REPLACE: Your Chapter Title"
    chapter_label_name = slugify(title) if title != "REPLACE: Your Chapter Title" else "MyChapter"

    lines: list[str] = []
    used_labels: set[tuple[str, str]] = set()
    _emit_copyright(lines)
    _emit_author_setup(lines, chapter, chabbr)
    _emit_chapter_title(lines, title, chapter_label_name)
    _emit_writeauthors(lines, chapter, title, chapter_label_name)
    _emit_learning_objectives(lines, chapter)
    lines.append("")
    lines.append("% ###################################################################")
    lines.append("% CHAPTER CONTENT STARTS HERE")
    lines.append("% ###################################################################")
    lines.append("")
    for section in chapter.sections:
        _emit_section(lines, section, used_labels=used_labels)
    lines.append("% ###################################################################")
    lines.append("% END OF CHAPTER")
    lines.append("% ###################################################################")
    _emit_todo_summary(lines, chapter)
    return "\n".join(lines) + "\n"


def generate_chapter_json(
    chapter: Chapter,
    chabbr: str | None = None,
    metadata: dict | None = None,
) -> str:
    """Generate the chapter.json metadata file.

    ``metadata`` keys override the defaults derived from ``chapter``. Only keys
    that appear in the default schema are accepted; others are ignored.
    """
    if not chabbr:
        chabbr = derive_chabbr(chapter.title or "MyChapter")

    toc = [s.title for s in chapter.sections if s.level == 1 and s.title]

    data = {
        "title": chapter.title or "REPLACE: Your Chapter Title",
        "authors": [
            f"{a.first} {a.last}".strip() or "REPLACE: Your Name"
            for a in chapter.authors
        ]
        or ["REPLACE: Your Name"],
        "description": "REPLACE: A brief description of this chapter.",
        "toc": toc or ["Introduction"],
        "entry_file": "MyChapter.tex",
        "cover_image": "cover.png",
        "keywords": [],
        "chapter_type": chapter.chapter_type,
        "chabbr": chabbr,
        "depends_on": [],
        "discipline": "mse",
        "published": False,
    }
    if metadata:
        for key, value in metadata.items():
            if key in data and value is not None:
                data[key] = value
    return json.dumps(data, indent=2, ensure_ascii=False) + "\n"


def generate_bib(entries: list[BibEntry]) -> str:
    """Generate a BibTeX .bib file from BibEntry objects."""
    if not entries:
        return _default_bib()
    parts = [
        "%% This BibTeX bibliography file was generated by OCconvert.",
        "%% Please verify all entries and add DOIs where missing.",
        "",
    ]
    for e in entries:
        if "doi" not in e.fields:
            parts.append(f"%% TODO: add DOI for {e.key}")
        parts.append(f"@{e.entry_type}{{{e.key},")
        for k, v in e.fields.items():
            parts.append(f"\t{k} = {{{v}}},")
        parts.append("}")
        parts.append("")
    return "\n".join(parts) + "\n"


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _default_bib() -> str:
    return (
        "%% This BibTeX bibliography file was generated by OCconvert.\n"
        "%% Add your references here in BibTeX format.\n"
        "%% Citation keys should use the format: lastnameYEARa\n"
        "%% Example: smith2026a\n"
        "%% All entries should include a DOI field.\n\n"
    )


def _unique_slug(
    used: set[tuple[str, str]] | None, label_type: str, base: str
) -> str:
    """Return a label slug unique within ``label_type``, appending letter suffixes.

    The OC convention forbids numerals in labels, so collisions are resolved with
    ``b``, ``c``, ``d`` … (first occurrence keeps the bare slug). If ``used`` is
    None, the base slug is returned unchanged — callers without a registry get
    the old behaviour.
    """
    base = base or "unnamed"
    if used is None:
        return base
    key = (label_type, base)
    if key not in used:
        used.add(key)
        return base
    for c in "bcdefghijklmnopqrstuvwxyz":
        cand = f"{base}{c}"
        k = (label_type, cand)
        if k not in used:
            used.add(k)
            return cand
    # More than 25 collisions on one base — fall back to two-letter suffixes.
    for c1 in "abcdefghijklmnopqrstuvwxyz":
        for c2 in "abcdefghijklmnopqrstuvwxyz":
            cand = f"{base}{c1}{c2}"
            k = (label_type, cand)
            if k not in used:
                used.add(k)
                return cand
    return base


def _emit_copyright(lines: list[str]) -> None:
    lines.append("%")
    lines.append("% ###################################################################")
    lines.append("%  Copyright (c) 2026, REPLACE: Your Name")
    lines.append("%  Editors: A.D. Rollett & M. De Graef")
    lines.append("%  All rights reserved.")
    lines.append("%")
    lines.append("% Licensed under the Creative Commons CC BY-NC-SA 4.0 License,")
    lines.append('% hereafter referred to as the "License"; you may not use this')
    lines.append("% document except in compliance with the License. You may obtain")
    lines.append("% a copy of the License at")
    lines.append("%     https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode")
    lines.append("% Unless required by applicable law or agreed to in writing, all")
    lines.append('% material distributed under the License is distributed on an')
    lines.append('% "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,')
    lines.append("% either express or implied. See the License for the specific")
    lines.append("% language governing permissions and limitations under the License.")
    lines.append("% ###################################################################")


def _emit_author_setup(lines: list[str], chapter: Chapter, chabbr: str) -> None:
    lines.append("")
    lines.append("% ###################################################################")
    lines.append("% AUTHOR SETUP — Edit the lines below")
    lines.append("% ###################################################################")
    lines.append("")

    if chapter.chapter_type == "foundational":
        lines.append(r"\corechapter{Yes}")
    else:
        lines.append(r"% Uncomment the next line ONLY if this is a foundational chapter:")
        lines.append(r"%\corechapter{Yes}")

    lines.append("")

    if chapter.authors:
        a = chapter.authors[0]
        author_str = f"{a.first} {a.last}".strip()
        inst = a.institution or "Your University"
        lines.append(f"\\OCchapterauthor{{{author_str}, {inst}}}")
    else:
        lines.append(r"\OCchapterauthor{REPLACE: Your Name, Your University}")

    lines.append("")
    lines.append(f"% TODO: verify this 6-character chapter abbreviation")
    lines.append(f"\\renewcommand{{\\chabbr}}{{{chabbr}}}")
    lines.append("")
    lines.append(r"\chapterimage{\noheaderimage}")
    lines.append("% TODO: create a chapter header image (2480 x 1240 px, 300 dpi, RGB)")
    lines.append("% and replace the line above with:")
    lines.append(f"% \\chapterimage{{\\graphicspath {chabbr}header.pdf}}")


def _emit_chapter_title(lines: list[str], title: str, label_name: str) -> None:
    lines.append("")
    lines.append("% ###################################################################")
    lines.append("% CHAPTER TITLE — Edit the title below")
    lines.append("% ###################################################################")
    lines.append(f"\\chapter{{{title}}}\\label{{\\chabbr:ch:{label_name}}}")


def _emit_writeauthors(
    lines: list[str], chapter: Chapter, title: str, label_name: str
) -> None:
    lines.append("")
    if chapter.authors:
        for a in chapter.authors:
            last = a.last or "REPLACE: Last"
            first = a.first or "REPLACE: First"
            dept = a.department or "REPLACE: Department"
            inst = a.institution or "REPLACE: University"
            email = a.email or "REPLACE: email@example.com"
            url = a.url or "REPLACE: https://homepage.example.com"
            lines.append(
                f"\\writeauthor{{\\chabbr:ch:{label_name}}}{{{title}}}"
                f"{{{last}}}{{{first}}}{{{dept}}}{{{inst}}}{{{email}}}{{{url}}}"
            )
    else:
        lines.append(
            f"\\writeauthor{{\\chabbr:ch:{label_name}}}{{{title}}}"
            "{REPLACE: Last}{REPLACE: First}{REPLACE: Department}"
            "{REPLACE: University}{REPLACE: email@example.com}"
            "{REPLACE: https://homepage.example.com}"
        )


def _emit_learning_objectives(lines: list[str], chapter: Chapter) -> None:
    lines.append("")
    lines.append("% ###################################################################")
    lines.append("% LEARNING OBJECTIVES")
    lines.append("% ###################################################################")
    lines.append("% TODO: write meaningful learning objectives for each section")
    lines.append(r"\begin{learningobjectives}")
    lines.append(r"{\begin{itemize}")

    verbs = ["Understand", "Learn", "Apply", "Derive", "Analyze", "Evaluate"]
    top_sections = [s for s in chapter.sections if s.level == 1]
    if not top_sections:
        lines.append(
            r"    \item[{\color{OCBurntOrange}\ref{\chabbr:sec:introduction}:}] "
            "Understand the basic concepts presented in this chapter"
        )
    else:
        for i, sec in enumerate(top_sections):
            verb = verbs[i % len(verbs)]
            label = slugify(sec.title) if sec.title else "unnamed"
            lines.append(
                f"    \\item[{{\\color{{OCBurntOrange}}\\ref{{\\chabbr:sec:{label}}}:}}] "
                f"{verb} ... % TODO: complete this objective"
            )

    lines.append(r"\end{itemize}}")
    lines.append(r"\end{learningobjectives}")


def _emit_section(
    lines: list[str],
    section: Section,
    depth: int = 0,
    used_labels: set[tuple[str, str]] | None = None,
) -> None:
    cmd = {0: "section", 1: "subsection", 2: "subsubsection"}.get(depth, "subsubsection")
    label_type = {0: "sec", 1: "ssec", 2: "sssec"}.get(depth, "sssec")
    base = slugify(section.title) if section.title else "unnamed"
    label_slug = _unique_slug(used_labels, label_type, base)

    lines.append(f"\\{cmd}{{{section.title}}}\\label{{\\chabbr:{label_type}:{label_slug}}}")
    lines.append("")

    for block in section.content:
        _emit_block(lines, block, used_labels=used_labels)

    for child in section.children:
        _emit_section(lines, child, depth + 1, used_labels=used_labels)

    lines.append("")


def _emit_block(
    lines: list[str],
    block: Block,
    used_labels: set[tuple[str, str]] | None = None,
) -> None:
    # Import here to avoid circular imports at module level
    from .model import CodeBlock, Equation, Figure, ListBlock, Paragraph, Table

    if isinstance(block, Paragraph):
        _emit_paragraph(lines, block)
    elif isinstance(block, Equation):
        _emit_equation(lines, block, used_labels)
    elif isinstance(block, Figure):
        _emit_figure(lines, block, used_labels)
    elif isinstance(block, Table):
        _emit_table(lines, block, used_labels)
    elif isinstance(block, ListBlock):
        _emit_list(lines, block)
    elif isinstance(block, CodeBlock):
        _emit_code(lines, block)


def _emit_paragraph(lines: list[str], para: Paragraph) -> None:
    # Check if this is a raw LaTeX comment (e.g., speaker notes, TODO markers)
    if (
        len(para.runs) == 1
        and not para.runs[0].bold
        and not para.runs[0].italic
        and para.runs[0].text.lstrip().startswith("%")
    ):
        lines.append(para.runs[0].text)
        lines.append("")
        return

    text = runs_to_latex(para.runs)
    if text.strip():
        lines.append(text)
        lines.append("")


def _emit_equation(
    lines: list[str], eq: Equation, used_labels: set[tuple[str, str]] | None = None
) -> None:
    base = slugify(eq.latex[:40]) if eq.latex else "eq"
    label_slug = _unique_slug(used_labels, "eq", base)
    lines.append(r"\begin{equation}")
    lines.append(f"    {eq.latex}")
    lines.append(f"    \\label{{\\chabbr:eq:{label_slug}}}")
    lines.append(r"\end{equation}")
    lines.append("")


def _emit_figure(
    lines: list[str], fig: Figure, used_labels: set[tuple[str, str]] | None = None
) -> None:
    fname = fig.output_filename or fig.source_path or "REPLACE.pdf"
    caption = fig.caption or fig.alt_text or "REPLACE: figure caption"
    # Prefer the (author-written) caption for the label; fall back to the image
    # filename stem so figures with empty captions still get distinct labels.
    base_src = fig.caption or Path(fname).stem or caption
    base = slugify(base_src[:30]) if base_src else "fig"
    label_slug = _unique_slug(used_labels, "fig", base)
    lines.append(r"\begin{figure}[htbp]")
    lines.append(r"    \centering")
    lines.append(f"    \\includegraphics[width=0.6\\textwidth]{{\\graphicspath {fname}}}")
    lines.append(
        f"    \\caption{{\\label{{\\chabbr:fig:{label_slug}}}{caption}}}"
    )
    lines.append(r"\end{figure}")
    lines.append("% TODO: replace with an editable PDF figure in chapter/pdf/")
    lines.append("")


def _emit_table(
    lines: list[str], table: Table, used_labels: set[tuple[str, str]] | None = None
) -> None:
    caption = table.caption or "REPLACE: table caption"
    base = slugify(caption[:30]) if caption else "table"
    label_slug = _unique_slug(used_labels, "tb", base)

    # Determine column count
    ncols = len(table.headers) if table.headers else (len(table.rows[0]) if table.rows else 2)
    col_spec = "l" + "c" * (ncols - 1)

    lines.append(r"\begin{table}[htbp]")
    lines.append(r"    \centering")
    lines.append(f"    \\caption{{\\label{{\\chabbr:tb:{label_slug}}}{caption}}}")
    lines.append(f"    \\begin{{tabular}}{{{col_spec}}}")
    lines.append(r"        \toprule")

    if table.headers:
        header_cells = [h.text for h in table.headers]
        lines.append("        " + " & ".join(header_cells) + r" \\")
        lines.append(r"        \midrule")

    for row in table.rows:
        cells = [c.text for c in row]
        lines.append("        " + " & ".join(cells) + r" \\")

    lines.append(r"        \bottomrule")
    lines.append(r"    \end{tabular}")
    lines.append(r"\end{table}")
    lines.append("")


def _emit_list(lines: list[str], lb: ListBlock) -> None:
    env = "enumerate" if lb.ordered else "itemize"
    lines.append(f"\\begin{{{env}}}")
    for item in lb.items:
        _emit_list_item(lines, item, indent=1)
    lines.append(f"\\end{{{env}}}")
    lines.append("")


def _emit_list_item(lines: list[str], item: ListItem, indent: int) -> None:
    prefix = "    " * indent
    text = runs_to_latex(item.runs)
    lines.append(f"{prefix}\\item {text}")
    if item.children:
        lines.append(f"{prefix}\\begin{{itemize}}")
        for child in item.children:
            _emit_list_item(lines, child, indent + 1)
        lines.append(f"{prefix}\\end{{itemize}}")


def _emit_code(lines: list[str], cb: CodeBlock) -> None:
    lines.append(r"\begin{verbatim}")
    lines.append(cb.code)
    lines.append(r"\end{verbatim}")
    lines.append("")


def _emit_todo_summary(lines: list[str], chapter: Chapter) -> None:
    lines.append("")
    lines.append("% ###################################################################")
    lines.append("% TODO SUMMARY (items requiring author attention)")
    lines.append("% ###################################################################")
    lines.append("% - [ ] Verify/change the \\chabbr 6-character code")
    lines.append("% - [ ] Write learning objectives for each section")
    lines.append("% - [ ] Create chapter header image (2480 x 1240 px, 300 dpi, RGB)")
    lines.append("% - [ ] Replace placeholder figures with editable PDF originals")
    lines.append("% - [ ] Review all auto-generated labels")
    lines.append("% - [ ] Review auto-converted equations for correctness")
    lines.append("% - [ ] Add \\index{} or \\indexit{} entries for key terms")
    lines.append("% - [ ] Add DOIs to all bibliography entries")
    lines.append("% - [ ] Fill in REPLACE: placeholders in copyright and author fields")
    lines.append("% - [ ] Fill in chapter.json metadata (description, keywords, depends_on)")
